services:
  - type: web
    name: ideasynergy
    env: node
    plan: free
    buildCommand: npm install && npm run build:safe
    startCommand: node --experimental-modules --es-module-specifier-resolution=node ./dist/server/index.js
    envVars:
      - key: IBM_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: VITE_WEBSOCKET_URL
        value: wss://${RENDER_EXTERNAL_HOSTNAME}/ws
    healthCheckPath: /health